/**
 * SophieHR.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressType } from './addressType';


export interface EmployeeAddress { 
    id?: string;
    createdDate?: string;
    updatedDate?: string;
    line1?: string | null;
    line2?: string | null;
    line3?: string | null;
    line4?: string | null;
    postcode?: string | null;
    county?: string | null;
    addressType?: AddressType;
}

